version: latest
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment :
      POSTGRES_USER: bs_user
      POSTGRES_PASSWORD: password_bs
      POSTGRES_DB: database_bs
    volumes:
      - ./bs_init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck :
      test: ["CMD","pg_isready", "-d", "database_bs", "-U", "bs_user"]
      interval: 5s
      retries: 5
    restart: always
  app:
    image: python:3.9
    volumes:
      - ./app:/home/app/
    working_dir: /home/app
    command: bash -c "
            pip install --upgrade pip
            && pip install -r requirements.txt
            && python app.py"
    depends_on:
      db:
          condition: service_healthy
    links:
        - db